version: '3.5'

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb-comments
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password1234
      MONGO_INITDB_DATABASE: readme-comments
    ports:
      - 27018:27017
    volumes:
      - ${COMMENTS_DB_DIR:-../../../db/comments}:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/readme-comments --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: mongo-express-comments
    ports:
      - 8082:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password1234
      ME_CONFIG_MONGODB_URL: mongodb://admin:password1234@mongodb:27017/
